"""add product constraints

Revision ID: 5db5af9e19a6
Revises: 958ed0e7b4df
Create Date: 2026-08-21 16:11:47.140122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db5af9e19a6'
down_revision: Union[str, Sequence[str], None] = '958ed0e7b4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_product_price_positive', 'products', 'price > 0')
    op.create_check_constraint('check_product_stock_nonnegative', 'products', 'stock >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_product_stock_nonnegative', 'products', type_='check')
    op.drop_constraint('check_product_price_positive', 'products', type_='check')
    # ### end Alembic commands ###
